### ISSUE TITLE
Upper bound and lower bound experiments

### ISSUE THREAD

**Issue by Kishaan** [arthurdouillard/dytox#11]
Hi, 

I would like to run DyTox model on different datasets. Could you please help me understand how to run the joint training (upper bound accuracy) and simple training without replay (lower bound accuracy) experiments? 

In addition, did you train for (num of epochs * num of tasks) for these two experiments? You trained every task for 500 epochs, did you train joint training with only 500 epochs or 500 times 10 tasks = 5000 epochs? 

Thank you!

**Comment by arthurdouillard** [comment]
Hi,

1. For joint training, simply specify the `initial_increment` to be the total amount of classes.

2. For without replay, set the `memory_size` to 0.

3. No, I've only tried "num of epochs" for the joint training model.

Hope that helps!
