### ISSUE TITLE
Accuracy variation with the CLIP model

### ISSUE THREAD

**Issue by vgthengane** [arthurdouillard/dytox#13]
I am trying to integrate the CLIP model with DyTox. The evaluation accuracy with default config for `task=0`, `after epoch=0`, and `num_gpus=4` is `60.5%`. 

When I add a single line 
```_clip_model, _clip_transform = clip.load("ViT-B/32", device=device)```
the accuracy jumps from `60.5%` to `75.0%`.

Similarly for 
```_clip_model, _clip_transform = clip.load("ViT-B/16", device=device)```
the accuracy is `73.5%`.

I only instantiate the CLIP model above the `scenario_train` loop [here ](https://github.com/arthurdouillard/dytox/blob/4da25c13ef34e827e5361f78dcda08811a413c74/main.py#L434)and did not change anything else. 

Do you have any idea what might be causing this issue?

Thanks,
Vishal

**Comment by arthurdouillard** [comment]
Hum I'm sorry but I don't understand what you're doing.

You said "_clip_model, _clip_transform = clip.load("ViT-B/32", device=device)", but what were you doing before then? Creating another ViT of different size?
