### ISSUE TITLE
support for 'dytox' backbone

### ISSUE THREAD

**Issue by GSHZhang** [arthurdouillard/dytox#18]
the 'args.model' here[https://github.com/arthurdouillard/dytox/blob/main/continual/factory.py](url) dose not seem to support 'dytox' ?

**Comment by arthurdouillard** [comment]
args.model define the backbone. Dytox can work with any backbone including transformer and resnet. See https://github.com/arthurdouillard/dytox/blob/main/options/model/cifar_dytox.yaml#L6
