### ISSUE TITLE
Confusing about the configurations

### ISSUE THREAD

**Issue by haoranD** [arthurdouillard/dytox#20]
Dear Authors,

Many thanks for such amazing work and I am very interested in your work.

Recently, It tried to run the code on two GPU via:

`bash train.sh 0,1 \
    --options options/data/cifar100_2-2.yaml options/data/cifar100_order1.yaml options/model/cifar_dytox.yaml \
    --name dytox \
    --data-path MY_PATH_TO_DATASET \
    --output-basedir PATH_TO_SAVE_CHECKPOINTS \
    --memory-size 1000
`

I am happy that I can successfully get the results you reported, which is 64.82 exactly.

![WechatIMG10](https://user-images.githubusercontent.com/25835953/224684694-9e0857c9-f757-4c5c-8205-56daf8bba93e.jpeg)

HOWEVER, I am still a bit confused, how can I get the result as around 70.20 reported in the paper?

Looking forward to your reply, and I would be truly grateful if you could help with this. Thank you.

Best,
Haoran

**Comment by arthurdouillard** [comment]
Those results were obtained with distributed memory while training with many GPUs (more than 2, thus giving more rehearsal than the white line with only 2 GPUs). 

Those gray results were the original results in the paper. They make sense as we limit the rehearsal per-process, however for a fair evaluation, I've gray them out, as you should compare with the other newer results instead.
