### ISSUE TITLE
Why joint accuracy differs in different incremental settings？

### ISSUE THREAD

**Issue by ChenJunzhi-buaa** [arthurdouillard/dytox#21]
Thanky for your good work! I have some question about the upper bound.
As below picture from your papper, joint accuracy differs in different incremental settings. However, joint accuracy has nothing to do with incremental setting？
What's more, it seems that joint accuracy with resnet18 on CIFAR100 is about 70. In some other papers such as DER, when saving all old data, the average of all learning steps is about 80, so the acc of the last step is lower than 80.
Can you give some explains？ Thank you very much!
![image](https://user-images.githubusercontent.com/77711950/224697382-24c0016d-502e-4944-a8e0-4938f4b74ac4.png)

**Comment by arthurdouillard** [comment]
For the joint, I'm reporting DER's metrics. Which indeed should have been the same, but i choose to report those for consistency.

I'm not sure about you mean in the second sentence. There is no "avg" for joint model, as it does only one phase. DER puts it as "avg" but it's a mistake from them.
