### ISSUE TITLE
The accuracy on 10steps to ImageNet100 and ImageNet1000

### ISSUE THREAD

**Issue by yuzhang0403** [arthurdouillard/dytox#22]
Hello, thank you for your code.
I used the setting of dytox for 10 steps, but I can’t got the true accuracy on 10 steps to ImageNet100 and ImageNet1000.
I ran the following command:
`bash train.sh 0,1 
    --options options/data/imagenet100_10-10.yaml options/data/imagenet100_order1.yaml options/model/imagenet_dytox.yaml 
    --name dytox 
    --data-path MY_PATH_TO_DATASET 
    --output-basedir PATH_TO_SAVE_CHECKPOINTS 
    --memory-size 2000
`

`bash train.sh 0,1 
    --options options/data/imagenet1000_100-100.yaml options/data/imagenet1000_order1.yaml options/model/imagenet_dytox.yaml 
    --name dytox 
    --data-path MY_PATH_TO_DATASET 
    --output-basedir PATH_TO_SAVE_CHECKPOINTS 
    --memory-size 20000
`

Here is the reproduction result for ImageNet100:
{"avg": 74.47, "las_acc": 64.56}

ImageNet1000 results are as follows:
{"avg": 69.87, "las_acc": 60.19}

I noticed that the average accuracy on both ImageNet100 and ImageNet1000 is about 1.5 lower than the results in the paper. Is this an acceptable error? If not, could you tell me the reason about it. Thank you.

**Comment by arthurdouillard** [comment]
Hi !

Thank your for your interest in our work :)

Have you look at https://github.com/arthurdouillard/dytox/blob/main/erratum_distributed.md ? By default the code uses the "distributed memory". I've updated new results (the gray out results were the original ones in the paper). 

Your 74.47 correspond to the 73.96 (so yours is even better!) in the first table in the link I've just gave. Note that the appendix of the arxiv paper was also updated to reflect those new numbers.
