### ISSUE TITLE
continuum imagenet loading potential bug

### ISSUE THREAD

**Issue by zhaoedf** [arthurdouillard/dytox#4]
when i train imagenet100, i got the following error, it seems somehow the data path has two "train".

![image](https://user-images.githubusercontent.com/48846150/168426384-df8c359c-2cf7-4048-8df7-6f2d08659dfc.png)

i don't know what to do, since i use the following command to run, which specifies the dataset path and the things inside the dataset path are listed as follows.

![image](https://user-images.githubusercontent.com/48846150/168426418-fe300b62-5c75-4b23-840b-55ea0a06b054.png)
![image](https://user-images.githubusercontent.com/48846150/168426423-2e7b0f93-80ac-4843-8a98-48cd677925aa.png)

besides, it has this problem on one of my server, while the other server doesn't have similar issues.

**Comment by arthurdouillard** [comment]
Hey,

I think you were using different versions of Continuum on each server, because you indeed found a recent bug that was not apparent in the Continuum version I've used for DyTox.

So either use the original continuum version (`1.0.27`), or download the latest one were I fixed the bug right now (`1.2.2`).

Thanks for your report!

**Comment by zhaoedf** [comment]
> Hey,
> 
> 
> 
> I think you were using different versions of Continuum on each server, because you indeed found a recent bug that was not apparent in the Continuum version I've used for DyTox.
> 
> 
> 
> So either use the original continuum version (`1.0.27`), or download the latest one were I fixed the bug right now (`1.2.2`).
> 
> 
> 
> Thanks for your report!

haha i happened to try uninstall and reinstall continuum right before your reply and the problem was solved. i was gonna close this issue, thinking it was my problem, but it turns out that is because your hotfix, lol.

anyway, thx a lot!
by the way, i follow and use continuum for quite a long time and find it really good for coding!

**Comment by arthurdouillard** [comment]
>  by the way, i follow and use continuum for quite a long time and find it really good for coding!

I'm super happy to hear that! Thanks 😍
