### ISSUE TITLE
imagenet-100 result cannot reproduce

### ISSUE THREAD

**Issue by zhaoedf** [arthurdouillard/dytox#6]
**for cifar and imagenet-1000, i can get similar results as what paper reported.
how ever, for imangenet-100 only, i cannot get the same result, with 3~4% deviation.**

the followings are my running scripts and experiment results.

## scipts

    bash train.sh 6,7
    --options options/data/imagenet100_10-10.yaml options/data/imagenet100_order1.yaml options/model/imagenet_dytox.yaml \
    --name dytox \
    --data-path ~/ilsvrc2012 \
    --output-basedir ./checkpoints

## results (i ran two times on different machines)
![image](https://user-images.githubusercontent.com/48846150/171088047-ed1872a5-d50c-4225-b8ff-ef96875dbffc.png)

![image](https://user-images.githubusercontent.com/48846150/171088097-f748f0f7-cb4e-42a9-afdc-b7176c85c44c.png)

i focus on both avg and last acc.

**Comment by arthurdouillard** [comment]
Hello, I've saw your issue. I'll first look into https://github.com/arthurdouillard/dytox/issues/5, which may (or not) explain your issue and #2 

I'll get back to you asap. Sorry for the inconvenience.

**Comment by zhaoedf** [comment]
> Hello, I've saw your issue. I'll first look into #5, which may (or not) explain your issue and #2
> 
> I'll get back to you asap. Sorry for the inconvenience.

ok, i totally understand.

**Comment by GengDavid** [comment]
Hi @arthurdouillard  
I also tried ImageNet-100 and got a similar result as @zhaoedf. 

BTW, I wonder that is it possible to share your trained checkpoints with us?

**Comment by GengDavid** [comment]
Hi all, I also tried ImageNet-1000 but got a lower result:(
I am using Pytorch 1.10.1, CUDA 10.1
<img width="744" alt="dytox_imgnet" src="https://user-images.githubusercontent.com/16283388/173517375-dd9306d3-8abc-4a3a-a534-a0ce1039770e.png">
I'll try to use a different Pytorch version and try again.

**Comment by arthurdouillard** [comment]
Please see [erratum](https://github.com/arthurdouillard/dytox/blob/main/erratum_distributed.md).
