### ISSUE TITLE
Task Incremental Setting on CIFAR100

### ISSUE THREAD

**Issue by prateeky2806** [arthurdouillard/dytox#8]
Hi, Thanks you for your amazing paper. I was wondering if this code can be used to run task-incremental setting on CIFAR100 dataset. If yes, can you please point me to the changes that are required in the config file and the command to run those experiments. 

Thanks,
Prateek

**Comment by arthurdouillard** [comment]
Hi,

Thanks for your interests!

Yes it could. Simplest solution would be to modify the loss (https://github.com/arthurdouillard/dytox/blob/main/continual/engine.py#L165) to only do a softmax/ce among classes of a sample's task id.

At test time, if you already know which tasks are the samples from, you can only use their respective task tokens.
